### ISSUE TITLE
TodoMVC 

### ISSUE THREAD

**Issue by tuannguyenminh2086** [FountainJS/generator-fountain-vue#17]
Hello, I just setup a TodoMVC examples by fountainjs. I run a command: npm run serve. The brower is blank and console have a message: 

Uncaught TypeError: _vue2.default.use is not a function
  at Object.<anonymous> (index.js:6)
    at __webpack_require__ (bootstrap 73631b4…:19)
    at Object.<anonymous> (index.js:5)
    at __webpack_require__ (bootstrap 73631b4…:19)
    at bootstrap 73631b4…:63
    at bootstrap 73631b4…:63

**Comment by dmitry-guryev** [comment]
Not only in TodoMVC, "Hello world app" — the same error

**Comment by tuannguyenminh2086** [comment]
@dmitry-guryev : It will be fix, if you upgrade the NODE.js.
